RLL/CookbookApp-master/CookbookApp-master/CookbookApp/Cookbook.WebUI/Controllers/IngredientTypeController.cs
using Cookbook.Core.Contracts;
using Cookbook.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cookbook.WebUI.Controllers
{
    public class IngredientTypeController : Controller
    {
        IRepository<IngredientType> context;//for inmemory transactions

        //constructor
        public IngredientTypeController(IRepository<IngredientType> context)
        {
            this.context = context;//initializes inmemory context
        }

        // GET: IngredienttypeManager
        public ActionResult Index()
        {
            List<IngredientType> ingredientTypes = context.Collection().ToList(); //sets context to list
            return View(ingredientTypes);//passes recipes to view
        }

        public ActionResult Create()
        {
            IngredientType ingredientType = new IngredientType();
            return View(ingredientType);
        }

        //creates end-point
        [HttpPost]
        public ActionResult Create(IngredientType ingredientType)
        {
            //check if data validation passed
            if (!ModelState.IsValid)
            {
                return View(ingredientType);//returns if data validation is unsuccessful
            }
            else
            {
                context.Insert(ingredientType); //adds the recipe
                context.Commit(); //saves changes to cache memory

                return RedirectToAction("Index");//redirects to index page
            }
        }

        public ActionResult Edit(string Id)
        {
            IngredientType ingredientTypeToEdit = context.Find(Id);//search(data) for recipe by id

            if (ingredientTypeToEdit == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                return View(ingredientTypeToEdit);//return recipe
            }
        }

        [HttpPost]
        public ActionResult Edit(IngredientType ingredientType, string Id)
        {
            IngredientType ingredientTypeToEdit = context.Find(Id);

            if (ingredientTypeToEdit == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                if (!ModelState.IsValid) //data validation test
                {
                    return View(ingredientTypeToEdit);//reload page
                }

                ingredientTypeToEdit.Type = ingredientType.Type;

                context.Commit();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(string Id)
        {
            IngredientType ingredientTypeToDelete = context.Find(Id);

            if (ingredientTypeToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                return View(ingredientTypeToDelete);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            IngredientType ingredientTypeToDelete = context.Find(Id);

            if (ingredientTypeToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                context.Delete(Id);//deletes from database
                context.Commit();//saves changes
                return RedirectToAction("Index");
            }
        }
    }
}

RLL/CookbookApp-master/CookbookApp-master/CookbookApp/Cookbook.WebUI/Controllers/RecipeCategoryManagerController.cs
using Cookbook.Core;
using Cookbook.Core.Contracts;
using Cookbook.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cookbook.WebUI.Controllers
{
    public class RecipeCategoryManagerController : Controller
    {
        IRepository<RecipeCategory> context;//for inmemory transactions
        
        //constructor
        public RecipeCategoryManagerController(IRepository<RecipeCategory> context)
        {
            this.context = context;//initializes inmemory context
        }

        // GET: RecipeCategoryManager
        public ActionResult Index()
        {
            List<RecipeCategory> recipeCategories = context.Collection().ToList(); //sets context to list
            return View(recipeCategories);//passes recipes to view
        }

        public ActionResult Create()
        {
            RecipeCategory recipeCategory = new RecipeCategory();
            return View(recipeCategory);
        }

        //creates recipeCategory
        [HttpPost]
        public ActionResult Create(RecipeCategory recipeCategory)
        {
            //check if data validation passed
            if (!ModelState.IsValid)
            {
                return View(recipeCategory);//returns if data validation is unsuccessful
            }
            else
            {
                context.Insert(recipeCategory); //adds the recipe
                context.Commit(); //saves changes to cache memory

                return RedirectToAction("Index");//redirects to index page
            }
        }

        public ActionResult Edit(string Id)
        {
            RecipeCategory recipeCategory = context.Find(Id);//search(data) for recipe by id

            if (recipeCategory == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                return View(recipeCategory);//return recipe
            }
        }

        [HttpPost]
        public ActionResult Edit(RecipeCategory recipeCategory, string Id)
        {
            RecipeCategory recipeCategoryToEdit = context.Find(Id);

            if (recipeCategoryToEdit == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                if (!ModelState.IsValid) //data validation test
                {
                    return View(recipeCategory);//reload page
                }

                recipeCategoryToEdit.Category = recipeCategory.Category;
                
                context.Commit();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(string Id)
        {
            RecipeCategory recipeCategoryToDelete = context.Find(Id);

            if (recipeCategoryToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                return View(recipeCategoryToDelete);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            RecipeCategory recipeCategoryToDelete = context.Find(Id);

            if (recipeCategoryToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                context.Delete(Id);//deletes from database
                context.Commit();//saves changes
                return RedirectToAction("Index");
            }
        }
    }
}

RLL/CookbookApp-master/CookbookApp-master/CookbookApp/Cookbook.WebUI/Controllers/RecipeManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cookbook.Core;
using Cookbook.Core.Contracts;
using Cookbook.Core.Models;
using Cookbook.Core.ViewModels;

namespace Cookbook.WebUI.Controllers
{
    public class RecipeManagerController : Controller
    {
        IRepository<Recipe> context;//for inmemory transactions
        IRepository<RecipeCategory> recipeCategories;
        IRepository<IngredientType> ingredientTypes;

        //constructor
        public RecipeManagerController(IRepository<Recipe> recipeContext, IRepository<RecipeCategory> recipeCategoryContext, IRepository<IngredientType> ingredientTypeContext) 
        {
            context = recipeContext;//initializes inmemory context
            recipeCategories = recipeCategoryContext;
            ingredientTypes = ingredientTypeContext;
        }

        // GET: RecipeManager
        public ActionResult Index()
        {
            List<Recipe> recipes = context.Collection().ToList(); //sets context to list
            return View(recipes);//passes recipes to view
        }

        public ActionResult Create()
        {
            RecipeManagerViewModel viewModel = new RecipeManagerViewModel();
            viewModel.recipeCategories = recipeCategories.Collection();
            viewModel.ingredientTypes = ingredientTypes.Collection();
            return View(viewModel);
        }

        //creates recipe
        [HttpPost]
        public ActionResult Create(Recipe recipe, HttpPostedFileBase file)
        {
            //check if data validation passed
            if (!ModelState.IsValid)
            {
                return View(recipe);//returns if data validation is unsuccessful
            }
            else
            {
                if(file != null)//check if file exist
                {
                    recipe.Image = recipe.Id + Path.GetExtension(file.FileName);//sets recipe image to prefix(recipeid) plus file name ext
                    file.SaveAs(Server.MapPath("//Content/RecipeImages//")+recipe.Image);//saves the photo to the disk
                }
                context.Insert(recipe); //adds the recipe
                context.Commit(); //saves changes to cache memory

                return RedirectToAction("Index");//redirects to index page
            }
        }

        public ActionResult Edit(string Id)
        {
            Recipe recipe = context.Find(Id);//search(data) for recipe by id
            
            if (recipe == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                RecipeManagerViewModel viewModel = new RecipeManagerViewModel();
                viewModel.recipe = recipe;
                viewModel.recipeCategories = recipeCategories.Collection();
                viewModel.ingredientTypes = ingredientTypes.Collection();
                return View(viewModel);//return recipe
            }
        }

        [HttpPost]
        public ActionResult Edit(Recipe recipe, string Id, HttpPostedFileBase file)
        {
            Recipe recipeToEdit = context.Find(Id);

            if (recipeToEdit == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                if (!ModelState.IsValid) //data validation test
                {
                    return View(recipe);//reload page
                }

                if (file != null)//check if file exist
                {
                    recipeToEdit.Image = recipe.Id + Path.GetExtension(file.FileName);//sets recipe image to prefix(recipeid) plus file name ext
                    file.SaveAs(Server.MapPath("//Content/RecipeImages//") + recipeToEdit.Image);//saves the photo to the disk
                }
                recipeToEdit.Name = recipe.Name;
                recipeToEdit.Category = recipe.Category;
                recipeToEdit.Description = recipe.Description;
                recipeToEdit.ServingSize = recipe.ServingSize;
                recipeToEdit.Calories = recipe.Calories;

                recipeToEdit.instruction1 = recipe.instruction1; recipeToEdit.instruction6 = recipe.instruction6;
                recipeToEdit.instruction2 = recipe.instruction2; recipeToEdit.instruction7 = recipe.instruction7;
                recipeToEdit.instruction3 = recipe.instruction3; recipeToEdit.instruction8 = recipe.instruction8;
                recipeToEdit.instruction4 = recipe.instruction4; recipeToEdit.instruction9 = recipe.instruction9;
                recipeToEdit.instruction5 = recipe.instruction5; recipeToEdit.instruction10 = recipe.instruction10;

                recipeToEdit.ingredient1 = recipe.ingredient1; recipeToEdit.ingredient6 = recipe.ingredient6;
                recipeToEdit.ingredient2 = recipe.ingredient2; recipeToEdit.ingredient7 = recipe.ingredient7;
                recipeToEdit.ingredient3 = recipe.ingredient3; recipeToEdit.ingredient8 = recipe.ingredient8;
                recipeToEdit.ingredient4 = recipe.ingredient4; recipeToEdit.ingredient9 = recipe.ingredient9;
                recipeToEdit.ingredient5 = recipe.ingredient5; recipeToEdit.ingredient10 = recipe.ingredient10;


                //recipeToEdit.Price = recipe.Price;

                context.Commit();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(string Id)
        {
            Recipe recipeToDelete = context.Find(Id);

            if (recipeToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                return View(recipeToDelete);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(Recipe recipe, string Id)
        {
            Recipe recipeToDelete = context.Find(Id);

            if (recipeToDelete == null) //if not found
            {
                return HttpNotFound();//issue an http error
            }
            else
            {
                context.Delete(Id);//deletes from database
                context.Commit();//saves changes
                return RedirectToAction("Index");
            }
        }
    }
}

RLL/CookbookApp-master/CookbookApp-master/CookbookApp/Cookbook.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cookbook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Recipe Manager", "Index", "RecipeManager")</li>
                    <li>@Html.ActionLink("Categories", "Index", "RecipeCategoryManager")</li>
                    <li>@Html.ActionLink("Ingredients", "Index", "IngredientType")</li>
                    <li><a href="https://mykitchencalculator.com/recipeconverter.html"\>Kitchen Calculator</a></li>
                </ul>
                
            </div>
            <div class="navbar-collapse collapse">
                
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right owner">
                        <li class="frcountli">
                            @if (ViewBag.FRCount != null)
                            {
                                <span class="glyphicon glyphicon-user red frnotif @User.Identity.Name"><span>@ViewBag.FRCount</span></span>
                            }
                            else
                            {
                                <span class="glyphicon glyphicon-user frnotif @User.Identity.Name"><span></span></span>
                            }
                            <ul id="frnotiful"></ul>
                        </li>
                        <li class="msgcountli">
                            @if (ViewBag.MsgCount > 0)
                            {
                                <span class="glyphicon glyphicon-comment red msgnotif @User.Identity.Name"><span>@ViewBag.MsgCount</span></span>
                            }
                            else
                            {
                                <span class="glyphicon glyphicon-comment msgnotif @User.Identity.Name"><span></span></span>
                            }
                            <ul id="msgnotiful"></ul>
                        </li>
                        <li class="name">@ViewBag.FullName</li>
                        <li class="logout">@Html.ActionLink("Logout", "Logout", "Account")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>